version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo:5
    restart: always
    ports:
      - ${MONGO_EXT_PORT}:27017
    environment:
      TZ: "${TZ}"
      MONGODB_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - ./mongodb:/data/db
